import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CssBaseline, ThemeProvider, createTheme } from '@mui/material';
import Navbar from "../src/components/Navbar";
import LanguageSwitcher from '../src/components/LanguageSwitcher';
import { Box } from '@mui/material';
import Footer from "../src/components/Footer";
import ClientLayout from "../src/components/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  palette: {
    primary: { main: '#FFD600' }, // желтый
    secondary: { main: '#1565C0' }, // синий
  },
  typography: {
    fontFamily: [geistSans.variable, geistMono.variable, 'sans-serif'].join(','),
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
